In [1]:
import numpy as np


In [3]:
#creating a matrix using numpy
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [6]:
 matrix_2 = np.array([[3,5,2],[34,63,67],[234,63,67]])
print(matrix_2)

[[  3   5   2]
 [ 34  63  67]
 [234  63  67]]


In [7]:
matrix_2.shape

(3, 3)

In [8]:
#creating matrices with random values
random_matrix = np.random.rand(3,3)

In [9]:
print(random_matrix)

[[0.0912319  0.08758329 0.29389467]
 [0.7953871  0.15745135 0.21506976]
 [0.01590444 0.83829699 0.14962757]]


In [10]:
#creating matrix with random integar 
random_integar_matrix = np.random.randint(100,size=(4,5))
print(random_integar_matrix)

[[26 16 86 74 23]
 [83 28 55  7 39]
 [75  4 34  8 71]
 [52 34 23 22  4]]


In [13]:
#matrix with all the values as 1
matrix_3 = np.ones([3,4],dtype=int)
print(matrix_3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [15]:
#null or zero matrix
null_matrix = np.zeros([4,4],dtype=int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
#identity matrix
identity_matrix = np.eye(3,3,dtype=int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [20]:
#transpose of a matrix
#matrix with random int value
a = np.random.randint(100,size=(4,5))
print(a)

[[81 14 30 84  1]
 [22 68  4 77 11]
 [98 92 22 99  0]
 [46 50 31 59 33]]


In [21]:
transpose_of_a =  np.transpose(a)
print(transpose_of_a)

[[81 22 98 46]
 [14 68 92 50]
 [30  4 22 31]
 [84 77 99 59]
 [ 1 11  0 33]]
