In [1]:
import numpy as np


In [2]:
#Matrix Additoon

In [5]:
matrix_1 = np.array([[2,3],[4,5]])
matrix_2 = np.array([[4,5],[6,7]])
matrix_3 = matrix_2+matrix_1
print(matrix_3)

[[ 6  8]
 [10 12]]


In [6]:
matrix_3.shape

(2, 2)

In [9]:
#create 2 matrices with random values
a = np.random.randint(10,size=(3,3))
b = np.random.randint(10,size=(3,3))
sum = np.add(a,b)
print(sum)

[[ 6 15 14]
 [ 5 12 13]
 [ 7  8 17]]


In [ ]:
#we get error when we want to add matrices that dont match the shape

In [10]:
#matrix subtraction

In [11]:
matrix_1 = np.array([[2,3],[4,5]])
matrix_2 = np.array([[4,5],[6,7]])
matrix_3 = matrix_2-matrix_1
print(matrix_3)

[[2 2]
 [2 2]]


In [12]:
#create 2 matrices with random values
a = np.random.randint(10,size=(3,3))
b = np.random.randint(10,size=(3,3))
sub = np.subtract(a,b)
print(sub)

[[-4  5  5]
 [ 2  1 -8]
 [ 4  3  0]]


In [13]:
#we get error when we want to add matrices that dont match the shape

In [16]:
#Multiplying a matrix with a scaler


In [15]:
a = 5
b = np.array([[3,4],[5,6]])
c = a*b
print(c)

[[15 20]
 [25 30]]


In [17]:
a = np.random.randint(10,size=(3,3))
x = 3
multiplied = np.multiply(a,x)
print(multiplied)

[[24  3  3]
 [15 15 18]
 [ 6 18  0]]


In [18]:
#Multiplying Two Matrix

In [20]:
#create 2 matrices with random values
a = np.random.randint(5,size=(3,4))
b = np.random.randint(5,size=(4,3))
product = np.dot(a,b)
print(product)

[[32 34 28]
 [15 13 14]
 [12 13 12]]


In [21]:
#we get error when we want to add matrices that dont match the shape

In [22]:
#Element wise Matrix Multiplication

In [23]:
a = np.random.randint(10,size=(3,3))
b = np.random.randint(10,size=(3,3))
product = np.multiply(a,b)
print(product)

[[27  3 40]
 [ 4 42 10]
 [36  0 18]]
